# Generated by Django 5.1.4 on 2025-02-04 22:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_rename_creditcards_creditcard_rename_loans_loan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Budget',
            new_name='BudgetItem',
        ),
        migrations.RenameField(
            model_name='budgetitem',
            old_name='percentagae_of_income',
            new_name='percentage_of_income',
        ),
    ]
