# Generated by Django 5.1.6 on 2025-02-11 03:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_rename_budget_budgetitem_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budgetitem",
            name="percentage_of_income",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
